### ISSUE TITLE
master reordering plugin fails

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11647]
Reordering a plugin (with drag-and-drop) fails, after hitting refresh (F5) the plugin is not on the expected order.

Done on a fresh install

**Comment by jeabakker** [comment]
maybe just an issue in presentation, using `Top` it didn't change position, but `Top` and `Up` are gone

**Comment by jeabakker** [comment]
`Top` and `Up` are gone on more plugins

**Comment by jeabakker** [comment]
plugins don't have a priority

**Comment by jdalsem** [comment]
with the upgrade test the plugins had the prio
- new plugins did not get prio
- after a reorder, the affected plugins lost their priority

**Comment by jdalsem** [comment]
@hypeJunction could you have a look?

**Comment by jdalsem** [comment]
might be, but it also happens on reorder (After an upgrade from 2.3) to the by reordering affected plugins. So not **just** on install

**Comment by hypeJunction** [comment]
Working on a fix

**Comment by jeabakker** [comment]
fixed in 9640d7ee40a96344ae9a1d8476739b1d8c4ac856

**Comment by RiverVanRain** [comment]
@jeabakker @jdalsem Issue is still in Elgg 3.2.3.


![plugins  320i ~1](https://user-images.githubusercontent.com/2176145/71831586-3f2a2b80-30ba-11ea-97d5-72bbe55fd99d.gif)

**Comment by jdalsem** [comment]
Will need to investigate if this is the same problem, but reopened to make sure we do not lose track of it

**Comment by jdalsem** [comment]
i have tried to reproduce this issue... regular operations work fine; also tested with all plugins with the same priority or with no (null) priority, but i am still unable to reproduce. We can't analyze this any further at this moment. Please let me know if you can get some more details (like the actual plugin priority changes in the database). Removing this from the milestone

**Comment by RiverVanRain** [comment]
@jdalsem Can you try on my production site directly?

Just installed Elgg v3.2.3
I've tried on Windows7-8-10/Debian9-10/Ubuntu19.10 using latest Chrome79/Firefox72/Brave/Midori.
Problem is still - i can't use drag'n'drop to re-order plugins.
Something is works when I disabling all caching and clean its but then issue is back again.

URL: https://myapp.wzm.me
login: myapp
pass: 12345678

**Comment by jdalsem** [comment]
@RiverVanRain it is not wise to post credentials... better reset the password and send it to my email jdalsem@coldtrick.com

**Comment by RiverVanRain** [comment]
@jdalsem It's not important for me. This is a demo site and I will delete it later. 
Anyway, I sent you new credentials.

**Comment by jdalsem** [comment]
@RiverVanRain can you check if https://github.com/Elgg/Elgg/pull/13056/files solves your problems?

**Comment by RiverVanRain** [comment]
I made changes to the code, cleared the system cache and reset OPcache even.
Unfortunately, the problem wasn't solved.

**Comment by jdalsem** [comment]
i have looked at your site and might have some clue on what is going wrong. I will try to recreate the circumstances on my own development environment and i will get back to you on this

**Comment by RiverVanRain** [comment]
Thanks for great support.
Just tested on the localhost with Elgg 3.3 - Debian 9/Apache/PHP 7.3/Maria DB 10.0
Same problem :\

**Comment by RiverVanRain** [comment]
Sad but this issue is still in Elgg 3.3.1

**Comment by RiverVanRain** [comment]
Just tested this [commit](https://github.com/jdalsem/Elgg/commit/b856c4496f3d72b5b3f3cd9be20fe6764a5235ba)  and LGTM
